SELECT UTL_INADDR.GET_HOST_ADDRESS FROM DUAL
UNION ALL
SELECT INSTANCE_NAME FROM V$INSTANCE
UNION ALL
SELECT CASE SF_GET_UNICODE_FLAG()
           WHEN '0' THEN 'GBK18030'
           WHEN '1' THEN 'UTF-8'
           WHEN '2' THEN 'EUC-KR'
       END
FROM DUAL
UNION ALL
SELECT CAST(SF_GET_CASE_SENSITIVE_FLAG() AS VARCHAR)
FROM DUAL
UNION ALL
SELECT CASE VALUE
           WHEN '0' THEN '否(0)'
           WHEN '1' THEN '是(1)'
       END
FROM V$PARAMETER
WHERE NAME LIKE 'LENGTH_IN_CHAR'
UNION ALL
SELECT CASE PARA_VALUE
           WHEN '0' THEN '默认0'
           WHEN '1' THEN '兼容ORACLE(1)'
       END
FROM V$DM_INI
WHERE PARA_NAME LIKE 'BLANK_PAD_MODE'
UNION ALL
SELECT CASE T.PARA_VALUE
           WHEN '0' THEN '默认0'
           WHEN '2' THEN '兼容ORACLE 2'
           WHEN '4' THEN '兼容MYSQL 4'
       END
FROM SYS."V$DM_INI" T
WHERE T.PARA_NAME LIKE 'COMPATIBLE_MODE'
UNION ALL
SELECT CAST(PAGE()/1024 AS VARCHAR)
FROM DUAL
UNION ALL
SELECT CAST(SF_GET_EXTENT_SIZE() AS VARCHAR)
FROM DUAL
UNION ALL
SELECT CONCAT(SVR_VERSION,' ',BUILD_VERSION)
FROM V$INSTANCE
UNION ALL
SELECT MODE$
FROM V$INSTANCE
UNION ALL
SELECT CAST(PERMANENT_MAGIC AS VARCHAR)
FROM V$INSTANCE
UNION ALL
SELECT ID_CODE
FROM DUAL
UNION ALL
SELECT TO_CHAR(CREATE_TIME,'YYYY-MM-DD')
FROM "SYS"."V$DATABASE"
UNION ALL
SELECT CAST(MAX(N_CPU) AS VARCHAR)
FROM SYS."V$SYSTEMINFO"
UNION ALL
SELECT CAST(MAX(TOTAL_PHY_SIZE)/1024/1024/1024 AS VARCHAR)
FROM SYS."V$SYSTEMINFO"
UNION ALL
SELECT CAST(MAX(TOTAL_DISK_SIZE)/1024/1024/1024 AS VARCHAR)
FROM SYS."V$SYSTEMINFO";
